server:
  port: 8087

spring:
  application:
    name: api-gateway

  cloud:
    gateway:
      routes:
        - id: auth-service
          uri: http://localhost:8083
          predicates:
            - Path=/auth/**,/oauth2/**,/login/**,/users/**

        - id: provider-service
          uri: http://localhost:8082
          predicates:
            - Path=/providers/**

        - id: appointment-service
          uri: http://localhost:8084
          predicates:
            - Path=/slots/**,/appointments/**

        - id: payment-service
          uri: http://localhost:8085
          predicates:
            - Path=/payments/**

      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins:
              - "http://localhost:3000"
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
              - OPTIONS
            allowedHeaders:
              - "*"
            allowCredentials: false
